-- MySQL Script generated by MySQL Workbench
-- Fri Nov 30 13:09:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_searchfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_searchfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_searchfood` DEFAULT CHARACTER SET utf8 ;
USE `db_searchfood` ;

-- -----------------------------------------------------
-- Table `db_searchfood`.`restaurant_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`restaurant_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `cnpj` CHAR(18) NOT NULL,
  `restaurant_phone` CHAR(14) NOT NULL,
  `address` VARCHAR(80) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `profile_picture` CHAR(45) NULL,
  `owner_name` VARCHAR(45) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `owner_email` VARCHAR(45) NOT NULL,
  `owner_phone` CHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_restaurants_restaurant_status_idx` (`status` ASC),
  CONSTRAINT `fk_restaurants_restaurant_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_searchfood`.`restaurant_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_categories_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_searchfood`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` VARCHAR(500) NOT NULL,
  `category_id` INT NOT NULL,
  `product_price` DOUBLE NOT NULL,
  `promotional_price` DOUBLE NULL,
  `product_photo` CHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menus_restaurants1_idx` (`restaurant_id` ASC),
  INDEX `fk_menus_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_menus_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_searchfood`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_searchfood`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`user_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` CHAR(2) NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile_picture` CHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_status1_idx` (`status` ASC),
  CONSTRAINT `fk_users_user_status1`
    FOREIGN KEY (`status`)
    REFERENCES `db_searchfood`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`price_calculation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`price_calculation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price_calculation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`variations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`variations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `variation_name` VARCHAR(45) NOT NULL,
  `maximum_choice` INT NOT NULL,
  `minimum_choice` INT NOT NULL,
  `price_calculation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variations_menus1_idx` (`product_id` ASC),
  INDEX `fk_variations_price_calculation1_idx` (`price_calculation` ASC),
  CONSTRAINT `fk_variations_menus1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_searchfood`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variations_price_calculation1`
    FOREIGN KEY (`price_calculation`)
    REFERENCES `db_searchfood`.`price_calculation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`variation_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`variation_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `variations` INT NOT NULL,
  `option` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variation_options_variations1_idx` (`variations` ASC),
  CONSTRAINT `fk_variation_options_variations1`
    FOREIGN KEY (`variations`)
    REFERENCES `db_searchfood`.`variations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`operating_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`operating_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operating_schedule_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_operating_schedule_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_searchfood`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_methods_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_payment_methods_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_searchfood`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_searchfood`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_searchfood`.`contributors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contributors_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_contributors_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_searchfood`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
